Все требования по ТЗ выполнены
EvgeniyUdin1979/java-filmorate pull request #20
Opened 2023-04-20 21:06 UTC by EvgeniyUdin1979

2023-04-20 21:10 UTC, ValentinaBuddha approved these changes

2023-04-21 16:49 UTC, Dmitry-E commented on src/main/java/ru/yandex/practicum/filmorate/storages/dao/DirectorDbStorage.java
> +        String sql = "DELETE FROM DIRECTOR WHERE ID = :ID";
вместо удаления записи, лучше добавить поле `DELETED `в таблицу и в методе removeById проставлять в это поле 
`String sqlQuery = "update FILMS SET DELETED = true WHERE FILM_ID = ?";`

Тогда в случае ошибочного удаления данные можно будет востановить.

2023-04-22 09:34 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Но есть несколько замечаний, которые необходимо исправить!

Желаю удачи!

2023-04-22 09:34 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/controllers/UserControllerTest.java
> +        upData("src/test/resources/files/userslist.txt", "/users");
А без `src/test` не работает?
По возможности лучше не писать абсолютный путь, если достаточно относительного

2023-04-22 09:34 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/controllers/UserControllerTest.java
> +@Sql(scripts = "file:src/test/resources/data/review/sql/cleanReview.sql")
Аналогично про `/src/test`

2023-04-22 09:34 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/controllers/UserControllerServiceTest.java
> +    @Test
Почему это тест, если здесь нет ни одной проверки?

2023-04-22 09:34 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/controllers/ReviewControllerTest.java
> +    public void failDeleteDislike(String pathVars, String expectedResponse) throws Exception {
В тестах можно не использовать модификаторы доступа.
Но если вы их не используете, то не используете везде, либо наоборот. 
Иначе каша получается

2023-04-22 09:34 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerWithSearchTest.java
> +    private void initDate() throws Exception {
А удалить эти данные после тестирования.

Вообще для инициализации состояния теста можно обратить внимание на аннотации `BeforeEach`, `AfterEach`, `BeforeAll`, `AfterAll`

2023-04-22 09:34 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/controllers/DirectorsTest.java
> +                }
С точки зрения ООП правильнее было бы 3 метода, написать, потому, что в будущем здесь может быть куча разной логики, а мы будем увеличивать ветки, и получим `God-method`.

https://en.wikipedia.org/wiki/God_object

2023-04-22 09:34 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/validate/ReleaseDateValidator.java
> +         */
Лучше вообще удалить, придерживаясь принципа KISS:
https://en.wikipedia.org/wiki/KISS_principle

Так как мы пользуемся системой контроля версий, то это всегда можно будет восстановить

2023-04-22 09:34 UTC, LexLippi commented on src/main/resources/schema.sql
> +  	CONSTRAINT DIRECTOR_UNIQUE UNIQUE ( NAME )
Не совсем корректное ограничение.
А если у нас есть режиссеры тезки?
Не хотелось бы сливать их в одного человека

2023-04-22 09:34 UTC, LexLippi commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS PUBLIC.FILM_X_DIRECTOR (
Зачем здесь `X`?)

2023-04-22 09:34 UTC, LexLippi commented on src/main/resources/schema.sql
> +    TIME_STAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Тоже бы добавил `NOT NULL`

2023-04-22 09:34 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public void deleteFilm(@PathVariable("id") String id) {
А почему идентификаторы строковые?
Есть в этом какой-то скрытый смысл?

2023-04-22 09:34 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/DirectorService.java
> +            throw new FilmRequestException("Режиссёра с данным id " + id + " не существует!", HttpStatus.NOT_FOUND);
Лучше переименовать ее в `RequestException` тогда

2023-04-22 09:34 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/DirectorService.java
> +        findById(String.valueOf(id));
Преобразования туда-сюда из строки в число мне непонятны

2023-04-22 09:34 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storages/dao/ReviewDbStorage.java
> +                "LIMIT ?;";
оператор `limit` не описан в стандарте языка SQL, лучше использовать `FETCH`

2023-05-02 14:30 UTC, merged